training:
  epochs: 300
  batch_size: 16
  seed: 42
  folds: 5
  device: "cuda"

model:
  architecture: "GCN"
  input_size: 384
  hidden_size: 32
  ratio: 1.00
  readout: "mean"

optimizer:
  weight_decay: 1.0e-6
  momentum: 0.9

data:
  dataset: "sarcoma_t1"
  dino_size: "small"
  n_views: 14
